/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blotteruno;

/**
 *
 * @author Kristian
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        label7 = new java.awt.Label();
        textField6 = new java.awt.TextField();
        Add = new java.awt.Button();
        button2 = new java.awt.Button();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textField7 = new java.awt.TextField();
        label8 = new java.awt.Label();
        textField8 = new java.awt.TextField();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setName(""); // NOI18N

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Name of Complainant :");
        panel1.add(label1);
        label1.setBounds(420, 490, 190, 40);

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        panel1.add(textField1);
        textField1.setBounds(610, 500, 250, 30);

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setText("Complain");
        panel1.add(label2);
        label2.setBounds(90, 180, 80, 20);

        textField2.setText("textField2");
        panel1.add(textField2);
        textField2.setBounds(190, 180, 670, 240);

        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setText("Contact No:");
        panel1.add(label3);
        label3.setBounds(560, 560, 100, 28);

        textField3.setText("textField3");
        panel1.add(textField3);
        textField3.setBounds(680, 560, 180, 30);

        label4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label4.setText("COMPLAIN FORM");
        panel1.add(label4);
        label4.setBounds(340, 30, 320, 50);

        label5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label5.setText("Complain No");
        panel1.add(label5);
        label5.setBounds(650, 440, 110, 28);

        textField4.setText("textField4");
        panel1.add(textField4);
        textField4.setBounds(760, 440, 100, 30);

        label6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label6.setText("Date FIled");
        panel1.add(label6);
        label6.setBounds(190, 440, 90, 30);

        textField5.setText("textField5");
        panel1.add(textField5);
        textField5.setBounds(280, 440, 110, 30);

        label7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label7.setText("Reported");
        panel1.add(label7);
        label7.setBounds(90, 110, 100, 30);

        textField6.setText("textField6");
        panel1.add(textField6);
        textField6.setBounds(190, 110, 180, 30);

        Add.setLabel("Add");
        panel1.add(Add);
        Add.setBounds(40, 570, 130, 50);

        button2.setLabel("Clear");
        panel1.add(button2);
        button2.setBounds(230, 570, 130, 50);

        jTabbedPane1.addTab("Complain", panel1);

        panel2.setLayout(null);

        panel3.setBackground(new java.awt.Color(204, 204, 204));
        panel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Seach Record");
        panel3.add(jLabel1);
        jLabel1.setBounds(410, 20, 150, 20);

        jLabel2.setText("Reported ");
        panel3.add(jLabel2);
        jLabel2.setBounds(301, 80, 70, 16);

        textField7.setText("textField7");
        panel3.add(textField7);
        textField7.setBounds(380, 70, 180, 30);

        label8.setText("Case No");
        panel3.add(label8);
        label8.setBounds(310, 130, 70, 20);

        textField8.setText("textField8");
        panel3.add(textField8);
        textField8.setBounds(380, 120, 110, 30);

        button3.setLabel("Search");
        panel3.add(button3);
        button3.setBounds(330, 180, 90, 40);

        button4.setLabel("Clear");
        panel3.add(button4);
        button4.setBounds(460, 180, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel3.add(jScrollPane1);
        jScrollPane1.setBounds(70, 250, 850, 402);

        panel2.add(panel3);
        panel3.setBounds(0, 0, 970, 670);

        jTabbedPane1.addTab("Search", panel2);

        getContentPane().add(jTabbedPane1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Add;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    // End of variables declaration//GEN-END:variables
}
